name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "Format & Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: true

      - name: Check Solidity formatting
        run: forge fmt --check

      - name: Check contract sizes
        run: forge build --sizes

  build:
    name: "Build & Compile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: true

      - name: Restore cached build
        uses: actions/cache/restore@v4
        id: cache-build-restore
        with:
          path: |
            cache
            out
          key: foundry-build-${{ hashFiles('src/**', 'lib/**', 'foundry.toml') }}
          restore-keys: |
            foundry-build-

      - name: Build contracts
        run: forge build

      - name: Cache build artifacts
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            cache
            out
          key: foundry-build-${{ hashFiles('src/**', 'lib/**', 'foundry.toml') }}

  test-unit:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: true

      - name: Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: |
            cache
            out
          key: foundry-build-${{ hashFiles('src/**', 'lib/**', 'foundry.toml') }}
          restore-keys: |
            foundry-build-

      - name: Restore RPC cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.foundry/cache/rpc
          key: rpc-cache-base-sepolia-unit-${{ github.run_id }}
          restore-keys: |
            rpc-cache-base-sepolia-unit-
            rpc-cache-base-sepolia-

      - name: Run unit tests
        run: forge test --match-path "test/Unit.t.sol" -vvv

      - name: Save RPC cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ~/.foundry/cache/rpc
          key: rpc-cache-base-sepolia-unit-${{ github.run_id }}

  test-integration:
    name: "Integration Tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: true

      - name: Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: |
            cache
            out
          key: foundry-build-${{ hashFiles('src/**', 'lib/**', 'foundry.toml') }}
          restore-keys: |
            foundry-build-

      - name: Restore RPC cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.foundry/cache/rpc
          key: rpc-cache-base-sepolia-integration-${{ github.run_id }}
          restore-keys: |
            rpc-cache-base-sepolia-integration-
            rpc-cache-base-sepolia-

      - name: Run integration tests
        run: forge test --match-path "test/Integration.t.sol" -vvv

      - name: Save RPC cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ~/.foundry/cache/rpc
          key: rpc-cache-base-sepolia-integration-${{ github.run_id }}

  coverage:
    name: "Test Coverage"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
          cache: true

      - name: Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: |
            cache
            out
          key: foundry-build-${{ hashFiles('src/**', 'lib/**', 'foundry.toml') }}
          restore-keys: |
            foundry-build-

      - name: Restore RPC cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.foundry/cache/rpc
          key: rpc-cache-base-sepolia-coverage-${{ github.run_id }}
          restore-keys: |
            rpc-cache-base-sepolia-coverage-
            rpc-cache-base-sepolia-

      - name: Run coverage
        run: |
          forge coverage \
            --report summary \
            --report lcov

      - name: Save RPC cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ~/.foundry/cache/rpc
          key: rpc-cache-base-sepolia-coverage-${{ github.run_id }}

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Filter coverage
        run: |
          lcov --remove lcov.info \
            'test/*' 'script/*' 'lib/*' \
            --output-file lcov.info \
            --rc branch_coverage=1

      - name: Generate coverage report
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: github.event_name == 'pull_request'
        with:
          delete-old-comments: true
          lcov-file: ./lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify minimum coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: ./lcov.info
          minimum-coverage: 90
